name: Deploy Feature Preview

on: pull_request

jobs:
  build:
    uses: ./.github/workflows/docker-build.yml
    with:
      environment: staging
    secrets: inherit

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Test outputs
        run: |
          echo "image-version=${{ needs.build.outputs.image-version }}"
          echo "image-tags=${{ needs.build.outputs.image-tags }}"
