name: Deploy Preview

on: pull_request

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('**/package-lock.json') }}

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: npm

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build
        env:
          REACT_APP_ALGOLIA_APP_ID: '${{ secrets.REACT_APP_ALGOLIA_APP_ID }}'
          REACT_APP_ALGOLIA_API_KEY: '${{ secrets.REACT_APP_ALGOLIA_API_KEY }}'

      - name: Deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_ARCHWAY_NETWORK }}'
          expires: 7d
          target: docs-archway
          projectId: archway-network